### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by Apollo201** [shenshen-hungry/Semantic-CNN#2]
Hello, 
I have run your code several times,noting was changed, but the accuracy only reaches 81.3% or so, What's wrong with me?

**Comment by shenshen-hungry** [comment]
@Apollo201 This code was only tested in Tensorflow v0.11.0 and v0.12.0. I guess some Api changed in v1.0.0 and above. Installing Tensorflow v0.12.0 can help you to get an correct accuracy.
Try: pip install tensorflow==0.12.0 or pip install tensorflow-gpu==0.12.0

**Comment by Apollo201** [comment]
Thanks for your comment and advice,I re-installed the tensorflow-0.12 and ran again from beginning today ,but the accuracy was still 81.3% or so, I wonder if the code is the final version which can produce the correct accuracy?Could you run it again?Thank you a lot^_^！

**Comment by shenshen-hungry** [comment]
After re-installing Tensorflow 0.12.0 and running the Github code on my pc and another server, I got accuracies around 82.0-82.2. I'm sorry that I have no idea to figure out what leads to your errors.

**Comment by Jun0413** [comment]
@shenshen-hungry The highest accuracy I can get among the 10-fold cv is around 83% yet strangely, I also got a final test accuracy fixed at around 81.3%. Due to some reasons, I couldn't use tensorflow 0.12.0, so I ran the code in tensorflow 1.4 and to accommodate that, I changed `line 172` in `cnn.py` to:
`h_pool = tf.concat(pooled_outputs, 3)`

**Comment by shenshen-hungry** [comment]
@Jun0413 Since a cv of MR only contains around 1000 sentences, 83% is not too strange. I'm very curious about why the final test accuracy can't achieve 82% with tensorflow (version >= 1.0.0). The codes on GitHub were tested with tensorflow (version == 0.12.0) under different settings, including a few random seeds. I'm going to check the codes and update the project with the latest tensorflow.
p.s.
I guess the version of numpy is another important factor.

**Comment by Jun0413** [comment]
@shenshen-hungry Thank you very much for your reply. Just for your information, I tried altering other `nb_epochs` such as 22, 30 and 35, and it did not help. My numpy version is `1.13.3`.

**Comment by shenshen-hungry** [comment]
Hi guys,
I updated codes. The program was tested on Ubuntu==18.04, Tensorflow==1.7.0, CUDA==9.0 and Numpy==1.14.2. The result with default demo.sh can achieve 0.82. If not, run cnn.py several times, since the size of MR is small and random numbers have a great impact on it.
